### ISSUE TITLE
Get error while running the app.

### ISSUE THREAD

**Issue by shankhadevpadam** [manojkumar3692/Vuejs-Authentication#1]
ERROR  Failed to compile with 1 errors                                                                               12:25:18 PM

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/home/padam/html/vuejs/Vuejs-Authentication/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/home/padam/html/vuejs/Vuejs-Authentication/node_modules/eslint/lib/config.js:260:26)
    at processText (/home/padam/html/vuejs/Vuejs-Authentication/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/home/padam/html/vuejs/Vuejs-Authentication/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/home/padam/html/vuejs/Vuejs-Authentication/node_modules/eslint-loader/index.js:211:17)
    at Object.module.exports (/home/padam/html/vuejs/Vuejs-Authentication/node_modules/eslint-loader/index.js:206:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by manojkumar3692** [comment]
try installing eslint globally 
npm install -g eslint 
--- or ---
try installing npm install eslint --save-dev

**Comment by shankhadevpadam** [comment]
Still get same error after install the eslint.
